package interpreteur;

/* Generated By:JavaCC: Do not edit this line. CompileurConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompileurConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOMBRE = 4;
  /** RegularExpression Id. */
  int EOL = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<NOMBRE>",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
